# Generated by Django 5.2.17 on 2026-09-24 05:07

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Profile = apps.get_model("accounts", "Profile")
    database = schema_editor.connection.alias

    for user in User.objects.using(database).only("id", "email").iterator():
        local_part = user.email.partition("@")[0]
        display_name = local_part.replace(".", " ").replace("_", " ").title()[:40]
        Profile.objects.using(database).create(
            user_id=user.pk,
            handle=f"m_{user.pk}",
            display_name=display_name,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "handle",
                    models.CharField(
                        max_length=24,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9_]{3,24}$", "Use 3–24 letters, numbers, or underscores."
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=40)),
                ("bio", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["created_at"], name="profile_created_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("handle"),
                        name="profile_handle_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.GreaterThanOrEqual(
                                django.db.models.functions.text.Length("handle"), 3
                            ),
                            django.db.models.lookups.LessThanOrEqual(
                                django.db.models.functions.text.Length("handle"), 24
                            ),
                        ),
                        name="profile_handle_length_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.GreaterThanOrEqual(
                                django.db.models.functions.text.Length("display_name"), 1
                            ),
                            django.db.models.lookups.LessThanOrEqual(
                                django.db.models.functions.text.Length("display_name"), 40
                            ),
                        ),
                        name="profile_display_name_length_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("bio", ""),
                            django.db.models.lookups.LessThanOrEqual(
                                django.db.models.functions.text.Length("bio"), 160
                            ),
                            _connector="OR",
                        ),
                        name="profile_bio_length_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
