# Generated by Django 5.2.17 on 2026-09-24 05:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="customization",
            field=models.JSONField(
                default=accounts.models.default_profile_customization,
                validators=[accounts.models.validate_profile_customization],
            ),
        ),
    ]
