# Generated by Django 5.2.17 on 2026-09-24 07:55

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to=social.models.story_image_upload_to)),
                ("caption", models.CharField(blank=True, max_length=160)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers"),
                            ("private", "Only me"),
                        ],
                        default="public",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=social.models.default_story_expiration),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["expires_at", "created_at"], name="story_expiry_created_idx"
                    ),
                    models.Index(fields=["author", "expires_at"], name="story_author_expiry_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("visibility__in", ["public", "followers", "private"])),
                        name="story_visibility_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("created_at"))),
                        name="story_expires_after_create",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("caption", ""),
                            django.db.models.lookups.LessThanOrEqual(
                                django.db.models.functions.text.Length("caption"), 160
                            ),
                            _connector="OR",
                        ),
                        name="story_caption_length_valid",
                    ),
                ],
            },
        ),
    ]
